services:
  postgres-pergunta:
    image: postgres
    container_name: postgres-pergunta
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
    ports:
      - "5440:5432"
volumes:
  postgres-data: